name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install --dev
    - name: Test with pytest
      run: |
        pipenv run pytest --cov=./
        pipenv run codecov
